# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ta_dynamics_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(881, 686)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 219);\n"
"border-right-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.ta_dyn_comboBox = QtWidgets.QComboBox(self.tab_3)
        self.ta_dyn_comboBox.setObjectName("ta_dyn_comboBox")
        self.horizontalLayout_4.addWidget(self.ta_dyn_comboBox)
        self.ta_dyn_clean_pushButton = QtWidgets.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ta_dyn_clean_pushButton.setFont(font)
        self.ta_dyn_clean_pushButton.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"background-color: rgb(255, 152, 138);")
        self.ta_dyn_clean_pushButton.setObjectName("ta_dyn_clean_pushButton")
        self.horizontalLayout_4.addWidget(self.ta_dyn_clean_pushButton)
        self.ta_dyn_save_pushButton = QtWidgets.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ta_dyn_save_pushButton.setFont(font)
        self.ta_dyn_save_pushButton.setStyleSheet("background-color: rgb(173, 180, 255);")
        self.ta_dyn_save_pushButton.setObjectName("ta_dyn_save_pushButton")
        self.horizontalLayout_4.addWidget(self.ta_dyn_save_pushButton)
        self.ta_dyn_exit_pushButton = QtWidgets.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ta_dyn_exit_pushButton.setFont(font)
        self.ta_dyn_exit_pushButton.setStyleSheet("background-color: rgb(105, 203, 255);")
        self.ta_dyn_exit_pushButton.setObjectName("ta_dyn_exit_pushButton")
        self.horizontalLayout_4.addWidget(self.ta_dyn_exit_pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.ta_dyn_graphicsView = PlotWidget(Form)
        self.ta_dyn_graphicsView.setMinimumSize(QtCore.QSize(0, 550))
        self.ta_dyn_graphicsView.setMaximumSize(QtCore.QSize(16777215, 800))
        self.ta_dyn_graphicsView.setStyleSheet("background-color: rgb(186, 186, 186);")
        self.ta_dyn_graphicsView.setObjectName("ta_dyn_graphicsView")
        self.gridLayout.addWidget(self.ta_dyn_graphicsView, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Transient Absorption Dynamics"))
        self.label.setText(_translate("Form", "Wavelength (nm)"))
        self.ta_dyn_clean_pushButton.setText(_translate("Form", "Clear"))
        self.ta_dyn_save_pushButton.setText(_translate("Form", "Save"))
        self.ta_dyn_exit_pushButton.setText(_translate("Form", "Exit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "TA Dynamics"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
